# Generated by Django 2.2 on 2019-01-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('inv_numh', models.CharField(max_length=30)),
                ('inv_numd', models.CharField(max_length=30)),
                ('inv_img', models.ImageField(upload_to='invoice_img')),
                ('inv_money', models.FloatField()),
                ('inv_date', models.DateField()),
                ('inv_class', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Invoice',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta_user_id', models.CharField(max_length=30)),
                ('sta_num', models.IntegerField()),
                ('sta_total_money', models.FloatField()),
                ('sta_average_money', models.FloatField()),
            ],
            options={
                'db_table': 'Statistics',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_phone', models.IntegerField()),
                ('user_img', models.ImageField(upload_to='user_img')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.DeleteModel(
            name='Dreamreal',
        ),
    ]
